from tkinter import*
from tkinter.ttk import*
class NewWindow(Toplevel):
    def__init__(self,master=None)
   super().__init__(master=master)
   self.title("New Window")
   self.geometry("1000*700")
   self.configure(bg="red")
   name=Label(self,text="Name")
   name.grid(row=0,column=0)
   e1=Entry(self).grid(row=0,column=0) 
   password=Label(self,text="password")
   password.grid(row=1,column=0)
   e2=Entry(self)
   e2.grid(row=1,column=1)
   submit=Button(self,text="Submit")
   submit.grid(row=4,column=0)
   label=Label(self,font=("arial 12 bold",
                          text="This is a new Window") 
                          label.pack()
master=Tk()
master.geometry("1500*1000*0*0")
master.configure(bg="pink")
label=Label(master.text="This is a new window")
label.pack(side=Top,pady=10,padx=0) 
btn=Button(master,text="Click to open a new window")
btn.bind("<Button>",lambda e:NewWindow(maste)) 
btn.pack(pady=10)
mainloop() 
                       